<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Amits-MacBook-Air.local" failures="1" tests="1" name="Surefire test" time="272.74" errors="0" timestamp="28 Feb 2022 20:57:24 GMT">
  <testcase classname="courgette.api.testng.TestNGCourgette" name="parallelRun" time="272.281">
    <failure type="courgette.runtime.CourgetteTestFailureException" message="There were failing tests. Refer to the Courgette html report for more details.">
      <![CDATA[courgette.runtime.CourgetteTestFailureException: There were failing tests. Refer to the Courgette html report for more details.
]]>
    </failure>
  </testcase> <!-- parallelRun -->
</testsuite> <!-- Surefire test -->
